"""Scan a firmware tree and draft harness/architecture.json (spec section 6.1)."""
import fnmatch
import posixpath
import re
from pathlib import Path

DEFAULTS = {
    "max_depth": 2,
    "deep_file_threshold": 30,
    "vendor_patterns": ["third_party", "vendor", "external", "*cmsis*", "drivers/stm32*", "lib/*"],
    "test_patterns": ["test", "tests", "unit_test", "unittest", "*_test", "test_*"],
}
GENERATED_RE = re.compile(r"@generated|generated by|do not edit", re.IGNORECASE)
GENERATED_SCAN_LINES = 20


def scan_settings(config):
    settings = dict(DEFAULTS)
    settings.update(config.get("architecture") or {})
    return settings


def _matches(path, patterns):
    parts = path.lower().split("/")
    candidates = ["/".join(parts[:index + 1]) for index in range(len(parts))] + parts
    return any(fnmatch.fnmatchcase(candidate, pattern.lower())
               for candidate in candidates for pattern in patterns)


def folder_counts(files):
    counts = {}
    for name in files:
        folder = posixpath.dirname(name)
        counts[folder] = counts.get(folder, 0) + 1
    return counts


def subtree_count(counts, folder):
    return sum(count for path, count in counts.items()
               if path == folder or path.startswith(folder + "/"))


def module_paths(files, settings):
    counts = folder_counts(files)
    depth = settings["max_depth"]
    chosen = set()
    for folder in counts:
        if not folder:
            continue
        parts = folder.split("/")
        if len(parts) <= depth:
            chosen.add(folder)
            continue
        ancestor = "/".join(parts[:depth])
        if subtree_count(counts, ancestor) > settings["deep_file_threshold"]:
            chosen.add(folder)
        else:
            chosen.add(ancestor)
    return sorted(chosen)


def classify(repo, folder, files, settings):
    if _matches(folder, settings["vendor_patterns"]):
        return "vendor"
    if _matches(folder, settings["test_patterns"]):
        return "test"
    for name in files:
        text = (Path(repo) / name).read_text(encoding="utf-8", errors="replace")
        head = "\n".join(text.splitlines()[:GENERATED_SCAN_LINES])
        if GENERATED_RE.search(head):
            return "generated"
    return "owned"
