import pytest

from arch_check import validate_architecture
from arch_scan import (DEFAULTS, back_edges, classify, draft_architecture, folder_counts,
                       include_dirs, module_paths, scan_settings)
from helpers import fake_config, make_fixture_repo


@pytest.fixture
def fw(tmp_path):
    return make_fixture_repo(tmp_path / "fw")


def test_scan_settings_merges_over_defaults():
    assert scan_settings({}) == DEFAULTS
    settings = scan_settings({"architecture": {"max_depth": 3}})
    assert settings["max_depth"] == 3 and settings["vendor_patterns"] == DEFAULTS["vendor_patterns"]


def test_folder_counts_groups_by_folder():
    counts = folder_counts(["src/app/main.c", "src/app/app_config.h", "src/hal/hal.c", "boot.c"])
    assert counts == {"src/app": 2, "src/hal": 1, "": 1}


def test_module_paths_stop_at_max_depth():
    files = ["src/app/main.c", "src/drivers/uart/uart.c", "src/drivers/spi/spi.c", "boot.c"]
    assert module_paths(files, scan_settings({})) == ["src/app", "src/drivers"]


def test_module_paths_go_deeper_for_large_folders():
    files = [f"src/drivers/uart/f{n}.c" for n in range(20)] + [f"src/drivers/spi/f{n}.c" for n in range(20)]
    settings = scan_settings({"architecture": {"deep_file_threshold": 30}})
    assert module_paths(files, settings) == ["src/drivers/spi", "src/drivers/uart"]


def test_classify_by_pattern_and_generated_marker(fw):
    settings = scan_settings({})
    assert classify(fw, "src/drivers", ["src/drivers/uart.c"], settings) == "owned"
    assert classify(fw, "third_party/cmsis", ["third_party/cmsis/Include/core_cm4.h"], settings) == "vendor"
    assert classify(fw, "test", ["test/test_uart.c"], settings) == "test"
    generated = fw / "src" / "gen"
    generated.mkdir()
    (generated / "registers.h").write_text("/* @generated by svd2c, do not edit */\n", encoding="utf-8")
    assert classify(fw, "src/gen", ["src/gen/registers.h"], settings) == "generated"


def test_include_dirs_put_owned_folders_first():
    files = ["third_party/cmsis/Include/core_cm4.h", "src/app/app_config.h", "src/app/main.c"]
    modules = {"src/app": {"kind": "owned"}, "third_party/cmsis": {"kind": "vendor"}}
    assert include_dirs(files, modules) == ["src/app", "third_party/cmsis/Include"]


def test_back_edges_finds_the_edge_that_closes_a_cycle():
    assert back_edges([("a", "b"), ("b", "c")]) == []
    assert back_edges([("a", "b"), ("b", "a")]) == [("b", "a")]


def test_draft_architecture_of_the_sample_tree(fw):
    arch, report = draft_architecture(fw, fake_config())
    assert validate_architecture(arch) == []
    assert sorted(arch["modules"]) == ["src/app", "src/drivers", "src/hal", "test", "third_party/cmsis"]
    assert arch["modules"]["third_party/cmsis"]["kind"] == "vendor"
    assert arch["modules"]["test"]["kind"] == "test"
    assert arch["modules"]["src/app"]["allowed_deps"] == ["src/drivers"]
    assert arch["grandfathered"] == ["src/hal -> src/app"]
    assert ("src/hal", "src/app") in report["observed"] and report["root_sources"] == []
